name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5 # Gunakan v5 untuk kompatibilitas terbaru
        with:
          go-version: '1.25'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest