name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Run GolangCI-Lint (Native)
        run: |
          # 1. Unduh linter langsung menggunakan modul Go (Anti-404)
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          
          # 2. Eksekusi linter dari direktori instalasi Go
          $(go env GOPATH)/bin/golangci-lint run ./... --timeout=5m

  security:
    needs: lint
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Menggunakan Gosec untuk memindai hardcoded credentials, SQL Injection, dll
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  test:
    needs: [lint, security]
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true # Mengaktifkan cache bawaan agar build lebih cepat

      - name: Download Dependencies
        run: go mod tidy

      # -race: Mendeteksi bentrok memori antar goroutine
      # -coverprofile: Menghasilkan laporan coverage
      - name: Run Tests with Race Detector
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      # Menyimpan laporan hasil test coverage sebagai artifact yang bisa diunduh
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage-report
          path: coverage.txt