name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master # Akan otomatis deploy setiap ada push ke branch master
  workflow_run:
    workflows: ["Continuous Integration"] # Must match the 'name' of the upstream workflow
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1 # Sesuaikan dengan region Anda
  REPO_NAME: logistics-repo
  IMAGE_NAME: logistics-api

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Autentikasi ke Google Cloud menggunakan JSON Key dari GitHub Secrets
    - name: Google Auth (Workload Identity)
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'
        token_format: 'access_token'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Konfigurasi Docker agar bisa push ke Artifact Registry GCP
    - name: Docker Auth
      run: |-
        echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ env.REGION }}-docker.pkg.dev

    # Build Docker Image menggunakan Dockerfile yang dibuat di tahap sebelumnya
    - name: Build Docker Image
      run: |-
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    # Push Image ke Artifact Registry
    - name: Push Docker Image
      run: |-
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    # Deploy ke Cloud Run
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        project_id: '${{ env.PROJECT_ID }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'
        service: logistics-api-service
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        # Gunakan flag ini agar Cloud Run bisa diakses publik tanpa autentikasi GCP
        flags: '--allow-unauthenticated'
        env_vars: |-
          APP_ENV=production
          APP_PORT=8080
          PASETO_SECRET_KEY=${{ secrets.PASETO_SECRET_KEY }}
          XENDIT_API_KEY=${{ secrets.XENDIT_API_KEY }}
          XENDIT_CALLBACK_TOKEN=${{ secrets.XENDIT_CALLBACK_TOKEN }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}

    # Tampilkan URL Cloud Run yang sudah live!
    - name: Show Output URL
      run: echo "App deployed to ${{ steps.deploy.outputs.url }}"